// Real Chromium screenshots of the application with intercepted, synthetic API responses.
// This is a documentation fixture, not a backend end-to-end test. No live workspace is accessed.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
const pathModule=require('node:path');
const root=process.env.STUDIO_WEB || pathModule.resolve(__dirname,'../../xdev-ai-studio/web');
const origin=process.env.STUDIO_URL || 'http://localhost:3116';
if(!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw new Error('Capture only supports a local Studio build.');
const out=pathModule.resolve(__dirname,'../src/assets/ai-studio');
fs.mkdirSync(out,{recursive:true});
const permissions=[...new Set(fs.readFileSync(root+'/lib/i18n/en.ts','utf8').match(/[a-z_]+:[a-z_]+/g).concat(['app:read','app:create','app:write','app:publish','app:delete','dataset:read','dataset:write','dataset:create','provider:manage','tool:manage','workspace:manage','member:manage','role:manage','memory:admin','log:read','audit:read','training:finetune','idp:manage','egress:manage','storage:manage','workspace:create','workspace:branding','pii:manage','app:update','app:run','app:configure','provider:read','workflow:review']))];
const version={id:'version-demo',version:1,model_id:'model-demo',model_name:'gpt-4o-mini',params:{temperature:0.3},system_prompt:'Help colleagues find answers in the staff handbook. Use the attached knowledge base. If information is missing, explain what is needed.',created_at:'2026-09-23T08:00:00Z'};
const app={tags:[],id:'demo',name:'Staff handbook assistant',description:'Example: answer questions about internal procedures.',icon:'📘',app_type:'chatbot',sensitivity:'internal',status:'active',has_published:true,model_name:'gpt-4o-mini',conversation_count:12,updated_at:'2026-09-23T08:00:00Z',draft:version,published:version};
const levels=[{level:0,code:'public',label:'Public',allows_external:true,is_default:false},{level:1,code:'internal',label:'Internal',allows_external:true,is_default:true}];
const model={id:'model-demo',model_name:'gpt-4o-mini',model_type:'llm',provider_name:'OpenAI',is_external:true,usable:true,enabled:true,status:'active',capabilities:{}};
const provider={id:'provider-demo',name:'OpenAI',provider_type:'openai',base_url:'https://api.openai.com/v1',is_external:true,status:'active',catalog_key:'openai',catalog_version:'0.2.0',model_types:['llm'],needs_config:false,max_sensitivity:'internal',credentials:[],models:[model]};
const routes={'admin-tenants':'/admin/tenants','admin-users':'/admin/users','admin-health':'/admin/health','admin-runtime':'/admin/runtime','admin-network':'/admin/network','admin-flags':'/admin/flags','tool-api':'/integrations/tools/api','tool-workflow':'/integrations/tools/workflow',egress:'/integrations/tools/egress','app-monitoring':'/apps/demo/monitoring',documents:'/datasets/handbook',retrieval:'/datasets/handbook/retrieval',marketplace:'/marketplace',pipeline:'/datasets/pipeline',extensions:'/integrations/extension',logs:'/apps/demo/logs',annotations:'/apps/demo/annotations',roles:'/settings/roles',storage:'/settings/storage',identity:'/settings/identity',external:'/settings/external-knowledge',models:'/integrations/model-provider',apps:'/apps',knowledge:'/datasets',sources:'/integrations/data-source',tools:'/integrations/tools/mcp',workflow:'/apps/flow/workflow',approvals:'/workflow/gates',publish:'/apps/demo/deploy',api:'/apps/demo/api-access',triggers:'/integrations/trigger',memory:'/memories',monitoring:'/monitoring',workspace:'/settings/workspace',security:'/settings/data-protection',settings:'/settings/branding',training:'/settings/training',account:'/account',admin:'/admin',editor:'/apps/demo',signin:'/signin',knowledgeCreate:'/datasets/create'};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
for(const locale of ['en','vi']){const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});await context.addCookies([{name:'hub_locale',value:locale,domain:new URL(origin).hostname,path:'/'}]);const page=await context.newPage();page.setDefaultTimeout(3000);let current='';const errors=[];page.on('pageerror',e=>errors.push(current+': '+e.stack));
await page.route('**/console/api/**',async r=>{const path=new URL(r.request().url()).pathname.split('/console/api')[1];let data=[];
if(path==='/me')data={account_id:'author-demo',name:'Demo author',email:'author@example.com',tenant_id:'tenant-demo',workspace_id:'workspace-demo',role:'owner',permissions,department_ids:[],clearance:9,mfa_enabled:false,mfa_satisfied:true,is_instance_admin:true};
else if(path==='/workspaces')data=[{id:'workspace-demo',name:'Documentation demo',slug:'documentation-demo'}];
else if(path.endsWith('/storage/objects'))data={items:[],truncated:false};
else if(path.endsWith('/storage'))data={bucket_name:'documentation-demo',status:'ready',error:null,bytes_used:4200000,object_count:3,measured_at:'2026-09-23T08:00:00Z',storage_limit_bytes:1073741824,pending_legacy:0};
else if(path==='/sensitivity-levels')data=levels;
else if(path==='/apps')data=[app,{...app,id:'flow',name:'Document review workflow',app_type:'workflow'}];
else if(/^\/apps\/(demo|flow)$/.test(path))data={...app,...(path.includes('flow')?{id:'flow',name:'Document review workflow',app_type:'workflow'}:{})};
else if(path==='/system-models')data={types:[{model_type:'llm',default_id:'model-demo',models:[model]}]};
else if(path==='/providers')data=[provider];
else if(path==='/provider-catalog')data=[{key:'openai',label:'OpenAI',provider_type:'openai',app_version:'0.2.0',catalog_version:'0.2.0',model_types:['llm'],installed:true,installed_count:1,default_base_url:'https://api.openai.com/v1',description_en:'Chat and embedding models',description_vi:'Mô hình hội thoại và embedding',credential_hint_vi:'',dev_only:false,is_external:true,credential_fields:[],configurate_methods:['predefined-model'],provider_credential_schema:{credential_form_schemas:[]}}];
else if(path.endsWith('/datasets')&&path.startsWith('/apps/'))data={datasets:[],warnings:[],retrieval_config:{}};
else if(path.endsWith('/tools')&&path.startsWith('/apps/'))data={tool_ids:[],operations:[],selected:{}};
else if(path==='/datasets/handbook')data={id:'handbook',name:locale==='vi'?'Sổ tay nhân viên':'Staff handbook',description:locale==='vi'?'Tài liệu minh họa':'Illustrative documents',indexing_technique:'high_quality',embedding_model_id:'embedding-demo',embedding_dimensions:1536,retrieval_config:{},pii_policy:{},sensitivity:'internal',document_count:0,word_count:0,status:'active',provider:'vendor',external_knowledge_id:'',department_id:null};
else if(path==='/datasets/handbook/documents')data={items:[],total:0,page:1,page_count:0};
else if(path==='/datasets')data=[{id:'handbook',name:'Staff handbook',description:'Example documents for a new assistant',icon:'📘',indexing_technique:'high_quality',embedding_model_id:'embedding-demo',embedding_dimensions:1536,retrieval_config:{},pii_policy:{},sensitivity:'internal',document_count:3,word_count:4200,status:'active',provider:'vendor',external_knowledge_id:'',department_id:null,updated_at:'2026-09-23T08:00:00Z'}];
else if(path==='/settings/pii-policy')data={policy:{entities:['EMAIL','PHONE'],replacement:'placeholder',on_error:'block',enabled:true,mask_person:true,mask_phone:true,mask_email:true,mask_id:true,never_mask:[],always_mask:[]}};
else if(path==='/settings/ner-policy')data={policy:{enabled:false,external_enabled:false,on_error:'block',max_chars:20000,external_url:'',external_secret_env:''},service_configured:false,effective_engine:'off'};
else if(path==='/settings/ocr-policy')data={policy:{enabled:true,external_enabled:false,mode:'auto'}};
else if(path==='/roles')data={roles:[],permissions:[],grantable:[]};
else if(path==='/workflow/gates/page')data={items:[],total:0};
else if(path==='/training/runners')data={available:['openai'],planned:[]};
else if(path==='/training/jobs')data={items:[]};
else if(path==='/instance/tenants')data={tenants:[],mfa_floor:false};
else if(path==='/instance/accounts')data={accounts:[]};
else if(path==='/instance/runtime-settings')data={settings:[],ttl_seconds:30,write_gate:'instance_admin'};
else if(path==='/instance/health')data={checks:{database:'ok',redis:'ok'},db_heads:['demo'],code_heads:['demo'],migration_ok:true,gate:'instance_admin',queues:{celery:0},queues_error:null,workers:['demo-worker'],workers_error:null};
else if(path==='/instance/network-zone')data={trust_proxy:false,real_ip_header:'X-Real-IP',real_ip_header_present:false,caller:{ip:'127.0.0.1',zone:'internal',ceiling:9},internal_cidrs:['127.0.0.0/8'],vpn_cidrs:[],vpn_max_label:2,internet_max_label:0,enforced:true,reason:null};
else if(path==='/instance/egress-allow')data={files:[],note:'Documentation fixture'};
else if(path==='/feature-flags')data={flags:{},catalog:[]};
else if(path==='/instance/settings')data={settings:[{name:'app_name',env:'XDEV_APP_NAME',secret:false,set:true,has_value:true,value:'Documentation demo',default:'XDev AI Studio',runtime_editable:false}],editable:false};
else if(path.endsWith('/share'))data={enabled:false,token:null,url:null,share_blocked_reason:null};
else if(path.includes('/workflow/draft'))data={graph:{nodes:[{id:'start',node_type:'start',config:{},position:{x:80,y:180}},{id:'llm',node_type:'llm',config:{model_id:'model-demo',prompt:'Summarize the supplied document.'},position:{x:430,y:180}},{id:'end',node_type:'end',config:{},position:{x:780,y:180}}],edges:[{source:'start',target:'llm'},{source:'llm',target:'end'}]},variables:[],env_keys:[],graph_token:'demo'};
else if(path==='/memory-admin/stats')data={days:30,outcomes:{created:12,khong:3,duplicate_db:2},verdicts:{accepted:8,proposed:4,rejected:0},accept_rate:1,by_app:[]};
else if(path==='/triggers')data={kinds:[{kind:'webhook',gate:'signature'},{kind:'schedule',gate:'cron'}],triggers:[]};
else if(path==='/workflow/event-definitions')data={items:[]};
else if(path==='/observability/usage')data={since:'2026-09-01',until:'2026-09-23',group:'day',buckets:[{key:'2026-09-21',turns:12,prompt_tokens:3000,completion_tokens:1800,total_tokens:4800,cost:0.02},{key:'2026-09-22',turns:18,prompt_tokens:4000,completion_tokens:2200,total_tokens:6200,cost:0.03}],totals:{turns:30,total_tokens:11000,cost:0.05}};
else if(path==='/observability/retrieval-quality')data={retrieved:0,approximate:0,exact:0};
else if(path==='/observability/feedback')data={liked:8,disliked:1,unrated:21,rated:9};
else if(path==='/observability/operations')data={window_hours:24,runs:{total:12,succeeded:12,failed:0,running:0,failure_rate:0},nodes:[],errors:[],triggers:{queued:0,running:0,done:12,dead:0,retried:0},queues:{celery:0},processes:{worker:'2026-09-23T08:00:00Z'},model_mismatch:[],degraded:{}};
else if(path==='/observability/quality')data={days:30,apps:[],rejections:[]};
else if(path==='/observability/spend')data={window_days:30,apps:[],workspaces:[]};
else if(path==='/observability/security')data={window_days:7,actions:[],events:[]};
else if(path==='/members')data=[{account_id:'author-demo',name:'Demo author',email:'author@example.com',role:'owner',status:'active',clearance:9,department_ids:[]}];
else if(path.includes('/quotas'))data={};
else if(path.includes('/branding'))data={};
console.log('API',current,path);
await r.fulfill({json:data});});
for(const [id,path]of Object.entries(routes)){if(process.env.ONLY&&!process.env.ONLY.split(',').includes(id))continue;current=id;try{await page.goto(origin+path);await page.waitForTimeout(1100);if(errors.length)throw new Error(errors.join('\n'));
const body=await page.locator('body').innerText();if(body.includes('This page couldn’t load'))throw new Error('Error screen: '+id);
await page.screenshot({path:`${out}/${id}.${locale}.png`});if(id==='apps'){await page.getByRole('button',{name:locale==='en'?'Create app':'Tạo ứng dụng',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('dialog').getByRole('textbox').first().fill(locale==='en'?'Staff handbook assistant':'Trợ lý sổ tay nhân viên');await page.waitForTimeout(150);await page.screenshot({path:`${out}/create-dialog.${locale}.png`});}console.log('SHOT',locale,id,(await page.locator('main').innerText().catch(()=>page.locator('body').innerText())).slice(0,140).replaceAll('\n',' | '));}catch(e){await browser.close();throw e}}
console.log('ERRORS',JSON.stringify(errors));await context.close();}await browser.close();})().catch(error=>{console.error(error);process.exitCode=1;});
